# Generated by Django 3.2.13 on 2022-06-01 10:41

import db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='limitClientOrderId',
            new_name='limit_client_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='newClientOrderId',
            new_name='new_client_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stopClientOrderId',
            new_name='stop_client_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='stopPrice',
            new_name='stop_price',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=db.fields.EnumField(blank=True, choices=[('SELL', 'Sell'), ('BUY', 'Buy')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=db.fields.EnumField(choices=[
                ('NEW', 'New'),
                ('ACTIVE', 'Active'),
                ('FILLED', 'Filled'),
                ('CANCELED', 'Canceled'),
                ('EXPIRED', 'Expired')
            ], default='NEW'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=db.fields.EnumField(blank=True, choices=[
                ('LIMIT', 'Limit'),
                ('MARKET', 'Market'),
                ('STOP_LOSS', 'Stop Loss'),
                ('STOP_LOSS_LIMIT', 'Stop Loss Limit'),
                ('TAKE_PROFIT', 'Take Profit'),
                ('TAKE_PROFIT_LIMIT', 'Take Profit Limit'),
                ('LIMIT_MAKER', 'Limit Maker')
            ], default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='callback_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='callback_status',
            field=db.fields.EnumField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started'), ('DONE', 'Done')],
                                      default='WAITING'),
        ),
        migrations.AddField(
            model_name='order',
            name='callback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_asset',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='result_quote_asset_quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
