# Generated by Django 3.2.13 on 2022-06-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0002_auto_20220601_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oco_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tbot.order'),
        ),
    ]
