# Generated by Django 3.2.13 on 2022-06-20 17:00

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0003_order_oco_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='callback_status',
            field=db.fields.EnumField(choices=[
                ('WAITING', 'Waiting'),
                ('STARTED', 'Started'),
                ('DONE', 'Done'),
                ('CANCELED', 'Canceled'),
                ('ERROR', 'Error')
            ], default='WAITING'),
        ),
    ]
