# Generated by Django 3.2.13 on 2022-06-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0004_alter_order_callback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commission_asset',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commission_quantity',
        ),
    ]
