# Generated by Django 3.2.13 on 2022-06-21 20:18

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0005_auto_20220620_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=db.fields.EnumField(choices=[('ON', 'On'), ('OFF', 'Off'), ('ERROR', 'Error')], default='OFF'),
        ),
    ]
