# Generated by Django 3.2.13 on 2022-06-22 19:26

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0006_bot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=db.fields.EnumField(choices=[('ON', 'On'), ('OFF', 'Off'), ('ERROR', 'Error'), ('CANCELED', 'Canceled')], default='OFF'),
        ),
    ]
