# Generated by Django 3.2.13 on 2022-06-29 13:17

import db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0008_auto_20220625_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='price_on_start',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='bot',
            name='step_type',
        ),
        migrations.AddField(
            model_name='order',
            name='result_filled_quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='bot',
            name='risk_target',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='risk_target_type',
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=db.fields.EnumField(
                choices=[('ON', 'On'), ('OFF', 'Off'), ('ERROR', 'Error'), ('CANCELED', 'Canceled'), ('DONE', 'Done')],
                default='OFF'),
        ),
    ]
