# Generated by Django 3.2.13 on 2022-07-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0009_auto_20220629_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='balance_allowance',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='balance_allowance_type',
        ),
    ]
