# Generated by Django 3.2.13 on 2022-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0010_auto_20220704_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='quote_quantity',
        ),
    ]
