# Generated by Django 3.2.13 on 2022-07-04 16:05

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0011_rename_quantity_order_quote_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='callback_status',
            field=db.fields.EnumField(choices=[('WAITING', 'Waiting'), ('STARTED', 'Started'), ('DONE', 'Done'), ('CANCELED', 'Canceled'), ('OCO_CANCELED', 'Oco Canceled'), ('ERROR', 'Error')], default='WAITING'),
        ),
    ]
