# Generated by Django 3.2.13 on 2022-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0012_alter_order_callback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
