# Generated by Django 3.2.13 on 2022-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0013_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='min_step',
            field=models.FloatField(default=0.001),
        ),
    ]
