# Generated by Django 3.2.13 on 2022-07-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0014_alter_profile_min_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='limit_client_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='new_client_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stop_client_order_id',
        ),
    ]
