# Generated by Django 3.2.14 on 2022-07-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0018_remove_bot_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='price_on_start',
        ),
    ]
