# Generated by Django 3.2.14 on 2022-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0019_remove_bot_price_on_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconnection',
            name='commission',
            field=models.FloatField(default=0.001),
        ),
    ]
