# Generated by Django 3.2.14 on 2022-07-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0020_exchangeconnection_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='multiplier_avg_price_minutes',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='multiplier_down',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='multiplier_up',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
