# Generated by Django 3.2.16 on 2023-01-15 15:05

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0024_bot_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconnection',
            name='exchange',
            field=db.fields.EnumField(choices=[('BINANCE', 'Binance'), ('BINANCETEST', 'Binancetest'), ('FAKE', 'Fake')], default='BINANCE'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='exchange',
            field=db.fields.EnumField(choices=[('BINANCE', 'Binance'), ('BINANCETEST', 'Binancetest'), ('FAKE', 'Fake')], default='BINANCE'),
        ),
    ]
