# Generated by Django 3.2.16 on 2023-01-25 19:27

import db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0025_auto_20230115_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='step_down_type',
            field=db.fields.EnumField(choices=[('PERCENT', 'Percent'), ('ABSOLUTE', 'Absolute')], default='ABSOLUTE'),
        ),
        migrations.AddField(
            model_name='bot',
            name='step_up_type',
            field=db.fields.EnumField(choices=[('PERCENT', 'Percent'), ('ABSOLUTE', 'Absolute')], default='ABSOLUTE'),
        ),
    ]
