"""
Django settings for tbot project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fy4^m1n%f+240#o-^)825yt8qjjp9q3@kl@#j59tnu+#4dc5)i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tbot'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
with open('/code/.env', 'r') as fh:
    vars_dict = dict(
        tuple(line.replace('\n', '').split('='))
        for line in fh.readlines() if not line.startswith('#')
    )

if vars_dict['_ENV'] == 'Development':
    DATABASES = {
        'default': {
            'ENGINE': 'db.connection',
            'NAME': 'tbot1',
            'USER': 'tbot1',
            'PASSWORD': 'tucBukComlipdofOgsopikkuquaychowrivFakVuwehawsIrEn',
            'HOST': 'db',
            'PORT': '3306',
        }
    }
elif vars_dict['_ENV'] == 'Production':
    DATABASES = {
        'default': {
            'ENGINE': 'db.connection',
            'NAME': 'tbot1',
            'USER': 'tbot1',
            'PASSWORD': 'tucBukComlipdofOgsopikkuquaychowrivFakVuwehawsIrEn',
            'HOST': '10.10.0.1',
            'PORT': '3306',
            'CONN_MAX_AGE': 3600,
        }
    }
elif vars_dict['_ENV'] == 'Test':
    DATABASES = {
        'default': {
            'ENGINE': 'db.connection',
            'NAME': 'tbot1test',
            'USER': 'tbot1',
            'PASSWORD': 'tucBukComlipdofOgsopikkuquaychowrivFakVuwehawsIrEn',
            'HOST': '10.10.0.1',
            'PORT': '3306',
            'CONN_MAX_AGE': 3600,
        }
    }
else:
    raise Exception('Env doesn\'t set')


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': 'host.docker.internal:11211',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RABBITMQ_HOST = 'rabbitmq'
RABBITMQ_USER_DS_CMD_QUEUE = 'user-data-streams-cmd'

EXCHANGE_ORDER_PREFIX = '7c071b84444e'

